import = ["~/.config/alacritty/oxocarbon-dark.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
multiplier = 3

[window]
padding = { x = 10, y = 10}
